version: "3.8"

networks:
  watchtower_network:
    driver: bridge

services:
  order-service:
    build: ./order-service
    container_name: ${ORDER_SERVICE_NAME:-order-service}
    ports:
      - "${ORDER_SERVICE_PORT:-3001}:${ORDER_SERVICE_PORT:-3001}"
    environment:
      - PORT=${ORDER_SERVICE_PORT:-3001}
    networks:
      - watchtower_network

  tracking-service:
    build: ./tracking-service
    container_name: ${TRACKING_SERVICE_NAME:-tracking-service}
    ports:
      - "${TRACKING_SERVICE_PORT:-3002}:${TRACKING_SERVICE_PORT:-3002}"
    environment:
      - PORT=${TRACKING_SERVICE_PORT:-3002}
    networks:
      - watchtower_network

  notification-service:
    build: ./notification-service
    container_name: ${NOTIFICATION_SERVICE_NAME:-notification-service}
    ports:
      - "${NOTIFICATION_SERVICE_PORT:-3003}:${NOTIFICATION_SERVICE_PORT:-3003}"
    environment:
      - PORT=${NOTIFICATION_SERVICE_PORT:-3003}
    networks:
      - watchtower_network

  prometheus:
    image: prom/prometheus:latest # fetch latest docker image for Prometheus
    container_name: prometheus
    ports:
      - "9090:9090" # expose Prometheus on port 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - watchtower_network